// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID            uuid.UUID
	MessageID     uuid.UUID
	Answer        string
	ReactionCount pgtype.Int8
	CreatedAt     pgtype.Timestamp
}

type Message struct {
	ID            uuid.UUID
	RoomID        uuid.UUID
	Message       string
	ReactionCount int64
	Answered      bool
	CreatedAt     pgtype.Timestamptz
}

type Room struct {
	ID        uuid.UUID
	Theme     string
	CreatedAt pgtype.Timestamptz
}
